### ISSUE TITLE
Prevent browser scrolling on touch device

### ISSUE THREAD

**Issue by hirbod** [B1naryStudio/ng-swippy#1]
When I drag, safari (on my iOS) will scroll.

**Comment by hirbod** [comment]
ping

**Comment by BogdanRusinka** [comment]
@Hirbod, sorry for the late answer, I will review this issue soon

**Comment by hirbod** [comment]
:+1:

**Comment by sdawson26** [comment]
This fixed it for me:

body {
  left: 0;
  -webkit-overflow-scrolling: touch;
  position: relative;
  top: 0;
  width: 100%;
  height: 100%;
  overflow: hidden;

}

html {
  overflow: hidden;
  -webkit-overflow-scrolling: touch;
}

**Comment by hirbod** [comment]
I switched to angular-swing, as this repo is dead
